world_api_map = {
    'us': 'world_us',
    'gbr': 'world_gbr',
    'gbrofs': 'world_gbrofs',
    'aut': 'world_aut',
    'bel': 'world_bel',
    'dnk': 'world_dnk',
    'fin': 'world_fin',
    'fra': 'world_fra',
    'deu': 'world_deu',
    'irl': 'world_irl',
    'ita': 'world_ita',
    'nld': 'world_nld',
    'nor': 'world_nor',
    'prt': 'world_prt',
    'esp': 'world_esp',
    'swe': 'world_swe',
    'che': 'world_che'
}
world_fund_type_map = {
    'us': 'FOUSA$$ALL',
    'gbr': 'FOGBR$$ALL',
    'gbrofs': 'FOGBR$$OFS',
    'aut': 'FOAUT$$ALL',
    'bel': 'FOBEL$$ALL',
    'dnk': 'FODNK$$ALL',
    'fin': 'FOFIN$$ALL',
    'fra': 'FOFRA$$ALL',
    'deu': 'FODEU$$ALL',
    'irl': 'FOIRL$$ALL',
    'ita': 'FOITA$$ALL',
    'nld': 'FONLD$$ALL',
    'nor': 'FONOR$$ALL',
    'prt': 'FOPRT$$ALL',
    'esp': 'FOESP$$ALL',
    'swe': 'FOSWE$$ALL',
    'che': 'FOCHE$$ALL'
}